### ISSUE TITLE
cannot open firefox on local to configure CycleCloud 

### ISSUE THREAD

**Issue by Clarkszw** [ltalirz/aiida-on-azure#5]
Hi Italirz,

Thanks for the instruction how to setting up Aiida in Azure.

I have met an issue to configure the cycle cloud server after install the Firefox in the new VM.

I am using the command in your instruction: 
`firefox -url=http://cycle_coud_domain_name:8080 -no-remote`

and get the response as:
`Error: no DISPLAY environment variable specified`

I have tried to google the solution, but I can't make it work.. could you help me on this:
1. `cycle_coud_domain_name` where can I find this? I guess the `coud` is a typo ? :)
2. how can I configure `DISPLAY` to make it work? I am using Mac OS Catalina 10.15.7

PS: `sudo echo 'deb https://packages.microsoft.com/repos/cyclecloud bionic main' > /etc/apt/sources.list.d/cyclecloud.list` will return an error about permission. I have used `sudo bash -c "echo 'something' > file.txt"` instead,

Thanks a lot in advance.
Have a nice day.
Best wishes
Clark

**Comment by ltalirz** [comment]
Hi @Clarkszw, thanks for your message.

I agree that the instructions

> If the CycleCloud server can be accessed from the public IP, one can use the browser from the local machine, otherwise one needs to install a browser in the VM

appear to be missing a step - namely: how the browser running on the VM is forwarded to your local machine (perhaps @JPchico can comment?).

I would like to point out that there actually _is_ a way to access the Cyclecloud dashboard from your local machine, even if the VM it is running on has no public IP address:
if you are using a virtual private network to access the VM, then it is of course straightforward (just use the private IP).

If you are using a bastion, you can forward the corresponding port to your local machine using the azure cli as follows:

```
az network bastion tunnel --name <name of cyclecloud vm> --target-resource-id /subscriptions/<...>/resourceGroups/<...>/providers/Microsoft.Compute/virtualMachines/<vm name> --resource-port 8080 --port 8080
```

Note: This is a relatively new feature, and in my experience the tunnel opened by it did not always work properly  https://github.com/Azure/azure-cli/issues/22562#issuecomment-1217861102 
As a workaround, one can use the azure cli to forward port `22` instead, and then use ssh to set up an SSH tunnel for port 8080 (`ssh -L 8080:localhost:8080 azureuser@localhost -i /path/to/private/key`). This works reliably.

**Comment by ltalirz** [comment]
> PS: `sudo echo 'deb https://packages.microsoft.com/repos/cyclecloud bionic main' > /etc/apt/sources.list.d/cyclecloud.list` will return an error about permission. I have used `sudo bash -c "echo 'something' > file.txt"` instead,

That's interesting... can you share the error message?

It's not quite clear to me how your approach would lead to different permissions... the only difference I see is that it forces the use of the `bash` shell (which usually is the default shell anyhow)

**Comment by Clarkszw** [comment]
> 

Hi Italirz,
Thanks for your reply:)
The permission error is
`-bash: cyclecloud.list: Permission denied`
I did it by ssh VM in Azure.

I searched the internet, the answer is:

The redirection is done by the shell before sudo is even started. So either make sure the redirection happens in a shell with the right permissions
`sudo bash -c 'echo "content" > file.txt'`
or use tee
`echo "content" | sudo tee file.txt`

https://askubuntu.com/questions/103643/cannot-echo-hello-x-txt-even-with-sudo

I am still checking what does `redirection` actually mean and the logic behind the scene, but it solved my case.

**Comment by Clarkszw** [comment]
> If you are using a bastion, you can forward the corresponding port to your local machine using the azure cli as follows:
> 
> ```
> az network bastion tunnel --name <name of cyclecloud vm> --target-resource-id /subscriptions/<...>/resourceGroups/<...>/providers/Microsoft.Compute/virtualMachines/<vm name> --resource-port 8080 --port 8080
> ```
> 
> Note: This is a relatively new feature, and in my experience the tunnel opened by it did not always work properly [Azure/azure-cli#22562 (comment)](https://github.com/Azure/azure-cli/issues/22562#issuecomment-1217861102) As a workaround, one can use the azure cli to forward port `22` instead, and then use ssh to set up an SSH tunnel for port 8080 (`ssh -L 8080:localhost:8080 azureuser@localhost -i /path/to/private/key`). This works reliably.

Thanks again @ltalirz for providing several solutions to address it.

But I am quite new about the idea of `forwarding` and `tunnel`, I can't totally get how to open the configuration page for the server.

Do you mean I need to run
`ssh -L 8080:localhost:8080 aiidamachineUsername@publicIPofaiidaVM -i /path/to/private/key`
to connect the aiida machine and then open my local browser "safari", use
`http://publicIPofVM:8080`
to open the configuration page for the CycleCloud server?

**Comment by Clarkszw** [comment]
> If you are using a bastion, you can forward the corresponding port to your local machine using the azure cli as follows:
> 
> ```
> az network bastion tunnel --name <name of cyclecloud vm> --target-resource-id /subscriptions/<...>/resourceGroups/<...>/providers/Microsoft.Compute/virtualMachines/<vm name> --resource-port 8080 --port 8080
> ```

I tried this as well, it returns
`(--resource-group | --ids) are required`
Then I add `--resource-group` and then change
`--name <name of cyclecloud vm>` to 
`--name <name of bastion>` it returns
`Defined port is currently unavailable`

**Comment by Clarkszw** [comment]
Hi @ltalirz, 
Can I ask what is 
`<cycle_coud_domain_name>`?
Is it the public ip/private ip of the 'aiida-machine'?
'aiida-machine' is used as a CycleCloud server?

**Comment by Clarkszw** [comment]
> Do you mean I need to run
> `ssh -L 8080:localhost:8080 aiidamachineUsername@publicIPofaiidaVM -i /path/to/private/key`
> to connect the aiida machine and then open my local browser "safari", use
> `http://publicIPofVM:8080`
> to open the configuration page for the CycleCloud server?

Hi @ltalirz,

I have opened the configuration page successfully..
Thanks for the advices. I have a better understanding about `forwarding` and `tunnelling` after this.

In my case, I use:
`ssh -L 8080:<private IP of aiida-machine>:8080 <username for aiida-machine>@<public IP of aiida machine> -i /path/to/private/key`
then I can open the CycleCloud dashboard in local browser by
`localhost:8080`

To anyone who is new to ssh forwarding, you can also have a look at
https://www.youtube.com/watch?v=N8f5zv9UUMI

There are two leftover questions, I will be really grateful if you can give me some clues:
1. How can I use Firefox to open the browser launch the dashboard as you have instructed? or to simplify the question, how to make this work
>I am using the command in your instruction:
>`firefox -url=http://cycle_coud_domain_name:8080 -no-remote`
>and get the response as:
>`Error: no DISPLAY environment variable specified`

2. You have mentioned in your linked comments, that you will call this issue as a bug, not an "lack of knowledge" issue. Could you help me understand this?

Thanks again and have a nice day:)
Clark

**Comment by JPchico** [comment]
Sorry about the late reply, I just moved and my new apartment has no internet yet. 

> How can I use Firefox to open the browser launch the dashboard as you have instructed? or to simplify the question, how to make this work

Due to the error that you have I think that the issue is that Ubuntu (server version) does not have the display manager installed (which is what defines what the DISPLAY variable is). You can install a display manager such as GNOME which will install the actual graphics and then this will allow you to run firefox in the VM as @ltalirz recommended.

Hope that helps! Will update the instructions and I'll add the missing step. I'm also working into automating this with terraform and ansible so hopefully that will make it easier.

**Comment by Clarkszw** [comment]
> You can install a display manager such as GNOME which will install the actual graphics and then this will allow you to run firefox in the VM as @ltalirz recommended.

Hi @JPchico 
Thanks for your instruction.
Unfortunately I have not got the luck to open the Firefox via ssh...
I have installed GNOME
`sudo apt install ubuntu-gnome-desktop`
then
`sudo apt update`
`sudo apt upgrade`
`sudo reboot`
when I try to open the Firefox locally (local MacOS, Catalina 10.15) it shows:
```
firefox
Error: no DISPLAY environment variable specified
```
Maybe you can help me point out the obvious missing step :)
Thanks a lot :)

**Comment by ltalirz** [comment]
Hi @JPchico , I'm also missing a detail in your instructions: you are installing a graphical window manager on the VM, but how do you then connect to it?
Are you using X-forwarding or a different mechanism like VNC?

**Comment by JPchico** [comment]
Hi! A couple of questions, @Clarkszw when you are connecting via ssh are you connecting with `ssh -X` or `ssh -Y` ? If you are not I think by default you should not be able to open any graphics.

Another option is to [install Xorg](https://askubuntu.com/questions/213678/how-to-install-x11-xorg) which is a bit more minimal than GNOME and usually has all you need for remote viewing. You might also need to install [xauth](https://askubuntu.com/questions/286649/run-a-remote-firefox-session-locally) I think that it is a requirement of Xorg but I'm not completely sure.

> Hi @JPchico , I'm also missing a detail in your instructions: you are installing a graphical window manager on the VM, but how do you then connect to it?
Are you using X-forwarding or a different mechanism like VNC?

@ltalirz Right now I'm just using normal ssh X-forwarding, but I tried XRDP which has a [nice guide in azure](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/use-remote-desktop?tabs=azure-cli). There are other tools such as remmina but they require to open certain ports which can make things a bit tricky with firewalls.

**Comment by Clarkszw** [comment]
Hi @JPchico,

Thanks for the reply.

I did not use `ssh -X` or `ssh -Y`...  After I installed [XQuartz](https://www.xquartz.org) for my MacOS and add `ssh -X` or `ssh -Y`, the DISPLAY variable error has gone. Instead:

```
clarkszw@aiida-machine$ firefox
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```
Then I did `sudo apt install libnvidia-gl-440` , the errors disappeared and it works fine. I can connect Cycle dashboard with Firefox remotely now.

I am not sure if it is normal that the response is quite slow. So I have to change back, using my own browser with forwarded port locally to do the setting in Dashboard.

But the Firefox in aiida-machine can be open via `ssh -X' and 'ssh -Y' with XQuartz installed on MacOS. 

Thanks a lot for the help @JPchico. Thanks to @ltalirz for the workaround by port forwarding.

Have a nice day to both.

**Comment by JPchico** [comment]
Hi @Clarkszw no problem! I will update the instructions to make sure that this step is present.

Regarding why it is slow, well it is because you are basically streaming the data via the ssh connection, and it will depend a lot on your network how fast it is. One thing that you can do to improve the speed is to use `ssh -X -C` the `-C` [option should compress ](https://www.unix.com/unix-for-advanced-and-expert-users/43112-ssh-c.html)the data before it being sent, this will make the performance a bit better.

**Comment by Clarkszw** [comment]
Good morning @JPchico,
Thanks for the tips on SSH connection. I am reading ssh documentation now to gain more knowledge of it. It is always nice to learn by doing.

Regarding the instruction. I have met a lot of issues when I try to install Aiida with my MacOS Catalina 10.15.7 This time is about XQuartz and `ssh -X`. I am not sure if it will be helpful to mention the operation system in the instruction, or maybe not necessary since really few people will use MacOS in the actual working environment with Aiida.
