### ISSUE TITLE
no credentials or managed identity flag provided when add subscription in CycleCloud dashboard

### ISSUE THREAD

**Issue by Clarkszw** [ltalirz/aiida-on-azure#6]
Hi @ltalirz,

I cannot add or finish the subscription because no credentials or managed identity flag provided for the Subscription ID when I configure in the CycleCloud dashboard.

Do you have any clue on this?

![Screenshot 2023-01-08 at 20 59 23](https://user-images.githubusercontent.com/110199757/211543756-677c4a9d-de80-47d0-9c3f-5e50cbe12f71.png)

Thanks in advance :)

**Comment by ltalirz** [comment]
Hi @Clarkszw , @JPchico's instruction mentions that he is using a service principal; detailed notes in  https://learn.microsoft.com/en-us/azure/cyclecloud/how-to/service-principals?view=cyclecloud-8

**Comment by Clarkszw** [comment]
Hi @ltalirz,
Thanks for your help.

@JPchico 's instruction is to assign the Contributor Role for the Subscription to the new CycleCloud Service Principal. I think it is following the step for [Quickstart - Install CycleCloud using the Marketplace image](https://learn.microsoft.com/en-us/azure/cyclecloud/qs-install-marketplace?view=cyclecloud-8).

For the manual installation, it will be nice to give an instruction, telling to enable the `aiida-machine` system assigned managed identity to finish 'add subscription' in Cycle Cloud dashboard setting.

Azure portal -> aiida-machine -> side menu 'Identity' -> System assigned -> Status 'on'
Set permissions by Azure role assignments.

Then the expected window will show in the CycleCloud Dashboard in a few minutes.

![Screenshot 2023-01-10 at 12 18 57](https://user-images.githubusercontent.com/110199757/211543548-a55575ad-aa05-49d2-8886-48bc3b53b8bd.png)
